### PR TITLE
Add baka command

### PR DESCRIPTION
**Pull request by jb1361**
I wanted a baka command.

### CODE REVIEW

**Comment by Devoxin** [comment]
Hm, while the code checks out, unfortunately the category **does not**. I've just checked what categories weeb.sh supports and `baka` is unfortunately not one of them.

**Comment by jb1361** [comment]
I assume that's where the api gets the random images?

**Comment by jb1361** [comment]
I shot an email to devs@weeb.sh. I'll get back to you if they arrange for that category to be added.

**Comment by jb1361** [comment]
Got in touch with Wolke from weeb.sh. I got him images to have the category added. Haven't heard back from him in a while, could you check if the category was added? Thank you.

**Comment by Devoxin** [comment]
image

**Comment by jb1361** [comment]
So the guy at weeb.sh essentially won't support the api. Would you be okay with me setting up a server with the system they use for the random image and using a proxy for random image with that type?

**Comment by jb1361** [comment]
Got an email from the guys at weeb.sh saying the image type was added. Could check to see if that was the case and possibly get this merged? Thank you.

**Comment by Devoxin** [comment]
`baka` endpoint is up and returning images related to the category. LGTM.

**Pull request merged**
